apiVersion: v1
kind: Service
metadata:
    name: "im-a-pod"
    labels:
        app: "im-a-pod.ntfrnzn.dev"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "im-a-pod.ntfrnzn.dev"